### ISSUE TITLE
Need a better packaging path for Linux

### ISSUE THREAD

**Issue by nickelpro** [SpockBotMC/RikerBot#1]
This issue is manly a reminder for myself of issues I've run into writing the setup.py file for RikerBot.

Riker is a weird project, it is supremely ill-suited for building with distutils and I have very little interest in supporting that workflow. This is fine for Windows where we can just distribute a binary wheel and be done with it, and that's the workflow that setup.py currently supports. But in the Linux world people want it both ways, they would like to install with PyPi _and_ compile things locally, which means distutils. 

I'm currently partial to the idea, that if you want Riker on Linux just build it yourself. Maybe in the future we can look into a Pkgbuild or something and install straight to site-packages, Python be damned. Or maybe someone will come along and make the build project work with distutils and I won't have to think about it.

**Comment by rom1504** [comment]
setting up github action to provide builds on pypi might be interesting
have a look at https://github.com/kyamagu/faiss-wheels which does something nice (in c++/python/swig too)

**Comment by nickelpro** [comment]
I'm closing this since `pip` can now build Rikerbot, which means the typical build path for Python modules on Linux works
