### ISSUE TITLE
SMPMap::get Rounding Errors with Negative Coordinates

### ISSUE THREAD

**Issue by olafurj** [SpockBotMC/RikerBot#9]
if you use SMPMap::get to get a x,y,z with a negative x or z, you end to lookup happens in the wrong chunk.
This is because x / 16 is not rounded the same way as x >> 4. 
Fixing this in SMPMap::get fixes the case -x,y,z but if z is negative, something else seems be wrong too, since I then get garbage instead of the exptected result.

One way to see this in action is to build a tower, and look for it under the player (loop surrounding blocks), there should be only 1 block in a plane under the player, if x is negative the coordinates of that block are shifted by 16, if z is negative block that should have air have garbage in them, guessing  there is something wrong with hashing of chunks

**Comment by nickelpro** [comment]
Thank you for filing the bug report here!

I'll explore this issue more fully, specifically the issues you see with Z, and hope to fix it in a patch set that also simplifies accessing individual block coordinates. I'm also hoping to massively simplify the Python API so you don't have to directly invoke the weird `PosArray` and `PosArrayVector` types.

I don't have a timeline for this stuff, but I hope to do some more Riker work over the Thanksgiving break. If you have a working patchset for any of these issues, feel free to PR.

**Comment by olafurj** [comment]
Hi,

maybe this saves some time, you can choose any kind of sequence pair ([],[],[]) or [(),(),()] etc:

PyObject* get(PyObject* v)
  {
        int i;
        std::vector<std::array<std::int32_t, 3>> positions;

        if (!PySequence_Check(v))
        {
            PyErr_SetString(PyExc_TypeError, "Expecting a sequence");
            return 0;
        }
        for (i=0;i<PyObject_Length(v);i++)
        {
            if (!PySequence_Check(PySequence_GetItem(v, i)))
            {
                PyErr_SetString(PyExc_TypeError, "Expecting a sequence of sequences");
                return 0;

            }
            PyObject* position=PySequence_GetItem(v,i);
            std::int32_t x=PyLong_AsLong(PySequence_GetItem(position,0));
            std::int32_t y=PyLong_AsLong(PySequence_GetItem(position,1));
            std::int32_t z=PyLong_AsLong(PySequence_GetItem(position,2));
             
            positions.push_back({x,y,z});
        }
        std::vector<std::uint16_t> blockids=get(positions);

        PyObject* result=PyList_New(blockids.size());
        for(i=0;i<blockids.size();i++)
        {
            PyList_SetItem(result,i,PyLong_FromLong(blockids[i]));
        }
        return result;
  }

----- Upprunaleg skilaboð -----
Frá: "Vito Gamberini" <notifications@github.com>
Til: "SpockBotMC/RikerBot" <RikerBot@noreply.github.com>
Cc: "ojb" <ojb@simnet.is>, "Author" <author@noreply.github.com>
Sent: Fimmtudagur, 5. Nóvember, 2020 20:58:46
Efni: Re: [SpockBotMC/RikerBot] negative coordinates round incorrectly in World (#9)

Thank you for filing the bug report here!

I'll explore this issue more fully, specifically the issues you see with Z, and hope to fix it in a patch set that also simplifies accessing individual block coordinates. I'm also hoping to massively simplify the Python API so you don't have to directly invoke the weird `PosArray` and `PosArrayVector` types.

I don't have a timeline for this stuff, but I hope to do some more Riker work over the Thanksgiving break. If you have a working patchset for any of these issues, feel free to PR.

**Comment by olafurj** [comment]
what I have found out so far is 

a block on x,z == 0,0
is matched by (0,0), (-1,-1),(-1,0) and (0,-1) so -1 seems to round down to zero
I also read through mineflyer, and found that bits_per_block < 8 in chunk update is bits_per_block <= 8 in mineflyer, not sure if it matters

what I mean by matched if you do a get on that coordinate, you get the same block_id as (0,0)

**Comment by olafurj** [comment]
think I know what is going on here, the the % function is not  working as expected in c++, it should return 15 but returns  -1 in -1 % 16

in python:
-1 % 16 = 15

in c++
-1 % 16 = -1

**Comment by olafurj** [comment]
after further testing I think % is not usable for negative coordinates, & 15 seems to work much better. Makes sense since we divide with 2 ^ 4

**Comment by olafurj** [comment]
this solves the problem, just change % 16 to & 15 for x and z

**Comment by nickelpro** [comment]
Fixed by https://github.com/SpockBotMC/RikerBot/pull/11, closing
